# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_g12
    environment:
      POSTGRES_DB: g12
      POSTGRES_USER: g12
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: