export const FLAG_MAP: Record<string, string> = {
  // Selecoes - Copa do Mundo 2026
  'África do Sul':   'assets/img/flags/national-team/africa.svg',
  'Alemanha':        'assets/img/flags/national-team/alemanha.svg',
  'Argélia':         'assets/img/flags/national-team/algeria.svg',
  'Arábia Saudita':  'assets/img/flags/national-team/arabia.svg',
  'Argentina':       'assets/img/flags/national-team/argentina.svg',
  'Austrália':       'assets/img/flags/national-team/australia.svg',
  'Áustria':         'assets/img/flags/national-team/austria.svg',
  'Bélgica':         'assets/img/flags/national-team/belgica.svg',
  'Bósnia':          'assets/img/flags/national-team/bosnia.svg',
  'Brasil':          'assets/img/flags/national-team/brasil.svg',
  'Cabo Verde':      'assets/img/flags/national-team/caboverde.svg',
  'Canadá':          'assets/img/flags/national-team/canada.svg',
  'Catar':           'assets/img/flags/national-team/catar.svg',
  'Colômbia':        'assets/img/flags/national-team/colombia.svg',
  'Coreia do Sul':   'assets/img/flags/national-team/coreia.svg',
  'Costa do Marfim': 'assets/img/flags/national-team/costamarfim.svg',
  'Croácia':         'assets/img/flags/national-team/croacia.svg',
  'Curaçao':         'assets/img/flags/national-team/curacao.svg',
  'Egito':           'assets/img/flags/national-team/egito.svg',
  'Equador':         'assets/img/flags/national-team/equador.svg',
  'Escócia':         'assets/img/flags/national-team/escocia.svg',
  'Espanha':         'assets/img/flags/national-team/espanha.svg',
  'Estados Unidos':  'assets/img/flags/national-team/eua.svg',
  'França':          'assets/img/flags/national-team/franca.svg',
  'Gana':            'assets/img/flags/national-team/gana.svg',
  'Haiti':           'assets/img/flags/national-team/haiti.svg',
  'Holanda':         'assets/img/flags/national-team/holanda.svg',
  'Inglaterra':      'assets/img/flags/national-team/inglaterra.svg',
  'Irã':             'assets/img/flags/national-team/ira.svg',
  'Iraque':          'assets/img/flags/national-team/iraque.svg',
  'Japão':           'assets/img/flags/national-team/japao.svg',
  'Jordânia':        'assets/img/flags/national-team/jordania.svg',
  'Marrocos':        'assets/img/flags/national-team/marrocos.svg',
  'México':          'assets/img/flags/national-team/mexico.svg',
  'Nova Zelândia':   'assets/img/flags/national-team/novazelandia.svg',
  'Noruega':         'assets/img/flags/national-team/noruega.svg',
  'Panamá':          'assets/img/flags/national-team/panama.svg',
  'Paraguai':        'assets/img/flags/national-team/paraguai.svg',
  'Portugal':        'assets/img/flags/national-team/portugal.svg',
  'RD Congo':        'assets/img/flags/national-team/congo.svg',
  'Tchéquia':        'assets/img/flags/national-team/republicatcheca.svg',
  'Senegal':         'assets/img/flags/national-team/senegal.svg',
  'Suécia':          'assets/img/flags/national-team/suecia.svg',
  'Suíça':           'assets/img/flags/national-team/suica.svg',
  'Tunísia':         'assets/img/flags/national-team/tunisia.svg',
  'Turquia':         'assets/img/flags/national-team/turquia.svg',
  'Uruguai':         'assets/img/flags/national-team/uruguai.svg',
  'Uzbequistão':     'assets/img/flags/national-team/uzbequistao.svg',
  // Clubes - Brasileirao
  'Athletico-PR':    'assets/img/flags/clubs/cap.svg',
  'Atlético‑MG':     'assets/img/flags/clubs/cam.svg',
  'Bahia':           'assets/img/flags/clubs/ecb.svg',
  'Botafogo':        'assets/img/flags/clubs/bfr.svg',
  'Bragantino':      'assets/img/flags/clubs/rb.svg',
  'Chapecoense':     'assets/img/flags/clubs/acf.svg',
  'Corinthians':     'assets/img/flags/clubs/sccp.svg',
  'Coritiba':        'assets/img/flags/clubs/cfc.svg',
  'Cruzeiro':        'assets/img/flags/clubs/cec.svg',
  'Flamengo':        'assets/img/flags/clubs/crf.svg',
  'Fluminense':      'assets/img/flags/clubs/ffc.svg',
  'Grêmio':          'assets/img/flags/clubs/gremio.svg',
  'Internacional':   'assets/img/flags/clubs/sci.svg',
  'Mirassol':        'assets/img/flags/clubs/mfc.svg',
  'Palmeiras':       'assets/img/flags/clubs/sep.svg',
  'Remo':            'assets/img/flags/clubs/cr.svg',
  'Santos':          'assets/img/flags/clubs/sfc.svg',
  'São Paulo':       'assets/img/flags/clubs/spfc.svg',
  'Vasco':           'assets/img/flags/clubs/crvg.svg',
  'Vitória':         'assets/img/flags/clubs/ecv.svg',
  'Ceará':           'assets/img/flags/clubs/ceara.svg',
  'Sport':           'assets/img/flags/clubs/sport.svg',
  'Fortaleza':       'assets/img/flags/clubs/fec.svg',
  'Juventude':       'assets/img/flags/clubs/jec.svg',
};

export function flagUrl(team: string): string | null {
  return FLAG_MAP[team] ?? null;
}
